// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: get_feed_by_url.sql

package database

import (
	"context"
)

const getFeedByUrl = `-- name: GetFeedByUrl :one
SELECT
    feeds.id, feeds.created_at, feeds.updated_at, feeds.name, feeds.url, feeds.user_id
FROM
    feeds
WHERE
    feeds.url = $1
`

func (q *Queries) GetFeedByUrl(ctx context.Context, url string) (Feed, error) {
	row := q.db.QueryRowContext(ctx, getFeedByUrl, url)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Url,
		&i.UserID,
	)
	return i, err
}
